### ISSUE TITLE
Google tasks not synced after initial sync

### ISSUE THREAD

**Issue by KylashTheKiller** [aantipov/notion-google-tasks-website#2]
Hi there, wonderful website btw. I've started using recently, and I realised that the tasks aren't syncing? (At least not for a good couple of minutes), and the time didn't sync over from google tasks? Could you help me out, thanks!

**Comment by aantipov** [comment]
Hi,
The tasks are synced every 5 minutes.
I checked the logs and there is indeed a problem.
The logs say that the selected Notion database is archived. Archived pages
can't be updated.
Please check and unarchive it.
If the problem persists, let me know.

> and the time didn't sync over from google tasks?
That's correct. It's one of the limitations which is listed on the website
- Google API doesn't provide reading/writing time unfortunately.
[image: image.png]

**Comment by KylashTheKiller** [comment]
Hi there, thanks for the superfast response!

To clarify on the archiving part, how exactly do I check for it and fix the issue? Also while here, could I also clarify if this link is 2 way, as in stuff added to the notion workspace gets added to tasks as well? Thanks!

**Comment by aantipov** [comment]
>To clarify on the archiving part, how exactly do I check for it and fix
the issue?

I dug deeper in the logs and it seems that it's not a Notion database, but
a particular task was deleted both in Google and Notion and there was some
kind of conflict.
I need to investigate it.
I'll let you know once I have results.

>this link is 2 way, as in stuff added to the notion workspace gets added
to tasks as well

Correct, 2-way. From Notion to Google and vice-versa

**Comment by aantipov** [comment]
@KylashTheKiller I found the bug and fixed it. Your syncing should be working now.
Thanks for reporting 👍

**Comment by KylashTheKiller** [comment]
Hi there, thanks for resolving the issue! One more question however, is it possible to use the checkbox on notion to mark a task as complete on google tasks, or is deleting the notion doc the only way? Thanks!

**Comment by aantipov** [comment]
You don't need to delete the Notion task to mark it as Complete
You tasks should have a _Status_ field with "To Do" and "Done" options.
You can display that field as Select or Checkbox.
![CleanShot 2024-02-05 at 12 07 46@2x](https://github.com/aantipov/notion-google-tasks-website/assets/427621/e6c4bd5a-31a3-4bfe-a9ee-057b6071465b)
<img width="676" alt="image" src="https://github.com/aantipov/notion-google-tasks-website/assets/427621/19540e30-c6d3-4a1f-8c0c-d1a30cfa8d18">

**Comment by KylashTheKiller** [comment]
Thank you so much for all the help! Wonderful website btw, saved a lot of trouble indeed!

**Comment by aantipov** [comment]
You are welcome! Feels great when people find it helpful 😄
