### ISSUE TITLE
Error when trying to sync with official sprint planning task database.

### ISSUE THREAD

**Issue by kyota-iino** [aantipov/notion-google-tasks-website#3]
Hello. Thanks for the very nice product.
This is the feature I have been waiting for.

Synchronization between Notion's newly created database for testing and Google Tasks was successful.

I already have a task management database in Notion that I created from an official Scrum template. Synchronization with that task database fails.

I have adjusted the necessary properties and status values as requested. But no matter how many times I try, the first sync between this database and Google Tasks fails.

![image](https://github.com/aantipov/notion-google-tasks-website/assets/26924886/1483d57d-7ec4-414d-a93e-08ebf1224ab2)

The error message appears when 80% of the tasks on the Google Tasks side have been synced to Notion.

The template for Scrum that I used has built-in sprint functionality that is currently in beta testing. This functionality is suspect, but I have not been able to verify it and am not certain.

Here are the details of the template.
https://www.notion.so/help/guides/product-engineering-notion-sprint-planning

The template itself should be available at https://www.notion.so/?tg=agile.

The reproduction procedure is as follows

1. Add the above template to your workspace.
2. Use the added "Tasks" database for synchronization. Add the necessary properties to it and change the status `In progress` to `To Do`.
3. Follow the instructions to connect your synchronization service with Google and Notion.
4. Select the database you have just synchronized.
5. It fails in the middle of synchronization.

Once I thought it was a bad idea to de-synchronize. But I checked the synchronization with the database that was first successfully synchronized after de-synchronization, a newly created one for testing, and it succeeded.

I think it would be very powerful if the already existing task database for sprints could be synchronized with Google Tasks bi-directionally.
I would be very happy if the cause is found and fixed.

**Comment by aantipov** [comment]
Hi there, 
thanks for the detailed description. 
I'm investigating the issue. I think I know the root cause.
I'll update you once I have something more concrete

**Comment by aantipov** [comment]
I fixed the issue. Should be fine now.
